# Generated by Django 3.2 on 2023-03-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230301_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Проверочный код для регистрации на сайте.', max_length=100, null=True, verbose_name='Код.'),
        ),
    ]
