# Generated by Django 3.2 on 2023-02-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Название произведения.', max_length=256, unique=True, verbose_name='Произведение.'),
        ),
    ]
