# Generated by Django 3.2 on 2023-02-28 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230228_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'Произведение.', 'verbose_name_plural': 'Произведения.'},
        ),
    ]
